### ISSUE TITLE
Text is raised

### ISSUE THREAD

**Issue by Govindbetterlives** [desconexo/highlight_text#21] opened 2021-10-27 07:18 UTC
It is raised below the level of the following text.
![highlight](https://user-images.githubusercontent.com/81243940/139018284-ff9d535f-347f-4385-a24d-7292c0e965d3.png)

**Comment by timmydan** [comment] 2021-11-24 07:26
Duplicate of #17 
I faced the same problem ([issue #17)](https://github.com/desconexo/highlight_text/issues/17#issuecomment-940757092), but found a way around. See if that works for you. I'm still not sure what causes the problem, but at least it can be avoided.

**Closed** 2022-01-12 16:53 UTC
