### ISSUE TITLE
Highlight not showing on overflowed text

### ISSUE THREAD

**Issue by myxzlpltk** [desconexo/highlight_text#30] opened 2022-07-04 10:23 UTC
Hi, I have some app that has UI like this. 
![highlight text](https://user-images.githubusercontent.com/59659668/177135100-1cf40ef9-d62d-4c28-a77b-2783775c1f58.png)

The problem is, the highlighted part won't show on overflowed text. My code probably something like this.
```dart
TextHighlight(
    text: 'Aditya Putra Pratama',
    words: {
        'pratama': HighlightedWord(
          decoration: BoxDecoration(
            color: Colours.yellow,
            borderRadius: BorderRadius.circular(3),
          ),
          padding: EdgeInsets.symmetric(horizontal: 2),
        ),
    },
    maxLines: 1,
    overflow: TextOverflow.ellipsis,
    textAlign: TextAlign.center,
)
```

**Comment by desconexo** [comment] 2022-08-16 20:09
Hi, I can't reproduce. Can you try on a new project and share the code, please?

**Comment by desconexo** [comment] 2022-10-21 11:30
closing due to lack of information

**Closed by desconexo** 2022-10-21 11:30 UTC
